/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lib_encrypt_ndk_EncryptUtile */

#ifndef _Included_com_lib_encrypt_ndk_EncryptUtile
#define _Included_com_lib_encrypt_ndk_EncryptUtile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lib_encrypt_ndk_EncryptUtile
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lib_encrypt_ndk_EncryptUtile_encrypt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_lib_encrypt_ndk_EncryptUtile
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lib_encrypt_ndk_EncryptUtile_decrypt
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
